[package]
name = "oberst"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/lionrexhepi/oberst"
homepage = "https://github.com/lionrexhepi/oberst"
readme = "../README.md"
license = "MIT"



[dependencies]
oberst_proc = { path = "./oberst_proc" }